apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-guest-book-cell-2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cell2
    name: in-cluster
  project: project-cell-2
  source:
    path: overlays/cell-2/guest-book
    repoURL: https://https://github.com/jdellostritto/k8s-ideal-goggles
    targetRevision: HEAD
    