apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-guest-book-cell-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cell1
    name: in-cluster
  project: project-cell-1
  source:
    path: overlays/cell-1/guest-book
    repoURL: https://github.com/jdellostritto/k8s-ideal-goggles
    targetRevision: HEAD
    