---
- op: replace
  path: /metadata/name
  value: game-2048-ingress
- op: replace
  path: /spec/ingressClassName
  value: ngrok
- op: replace
  path: /spec/rules
  value:
  - http:
      paths:
      - pathType: Prefix
        path: /2048
        backend:
          service:
            name: base-app-2048
            port:
              number: 80
      - pathType: Prefix
        path: /guest
        backend:
          service:
            name: base-guest-book
            port:
              number: 80
    host: summary-pipefish-above.ngrok-free.app