---
- op: add
  path: /metadata/annotations
  value: {
              "vgs.com/team": "UNDEFINED",
              "vgs.com/environment": "UNDEFINED",
              "vgs.com/customer": "UNDEFINED",
              "vgs.com/service": "UNDEFINED",
              "vgs.com/suite": "UNDEFINED",
              "vgs.com/department": "UNDEFINED",
              "vgs.com/criticality": "UNDEFINßED",
              "vgs.com/data-sensitivity": "UNDEFINED"
  }
- op: replace
  path: /metadata/name
  value: game-2048
- op: replace
  path: /metadata/labels
  value:
    app.kubernetes.io/name: game-2048
- op: replace
  path: /spec/selector/matchLabels
  value:
    app.kubernetes.io/name: game-2048
- op: replace
  path: /spec/template/metadata/labels
  value:
    app.kubernetes.io/name: game-2048
- op: replace
  path: /spec/template/spec/containers/0/name
  value: game-2048
- op: add
  path: /spec/template/spec/containers/0/ports
  value:
    - name: http
      containerPort: 80