---
- op: replace
  path: /spec/template/spec/containers/0/name
  value: base-keycloak-1
- op: replace
  path: /spec/template/spec/containers/0/imagePullPolicy
  value: Never
- op: add
  path: /spec/template/spec/containers/0/env
  value:
    - name: KC_DB
      valueFrom:
        secretKeyRef:
          name: keycloak-creds
          key: KC_DB
    - name: KC_DB_URL
      valueFrom:
        secretKeyRef:
          name: keycloak-creds
          key: KC_DB_URL
    - name: KC_DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: keycloak-creds
          key: KC_DB_USERNAME
    - name: KC_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: keycloak-creds
          key: KC_DB_PASSWORD
    - name: KC_HOSTNAME
      valueFrom:
        secretKeyRef:
          name: keycloak-creds
          key: KC_HOSTNAME
    - name: KEYCLOAK_ADMIN
      valueFrom:
        secretKeyRef:
          name: keycloak-creds
          key: KEYCLOAK_ADMIN
    - name: KEYCLOAK_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: keycloak-creds
          key: KEYCLOAK_ADMIN_PASSWORD
    - name: KC_HEALTH_ENABLED
      valueFrom:
        secretKeyRef:
          name: keycloak-creds
          key: KC_HEALTH_ENABLED
- op: add
  path: /spec/template/spec/containers/0/ports
  value:
    - name: http
      containerPort: 8080

