apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-appbundle-production
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    name: in-cluster
  project: appbundle-production
  source:
    path: apps/app-children/production
    repoURL: https://github.com/jdellostritto/k8s-ideal-goggles
    targetRevision: HEAD