apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-idp-keycloak-1
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: keycloak
    name: in-cluster
  project: project-keycloak-1
  source:
    path: apps/app-bundle/keycloak-1
    repoURL: https://github.com/jdellostritto/k8s-ideal-goggles
    targetRevision: HEAD