apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-appbundle-cell-3
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cell3
    name: in-cluster
  project: project-cell-3
  source:
    path: apps/app-bundle/cell-3
    repoURL: https://github.com/jdellostritto/k8s-ideal-goggles
    targetRevision: HEAD