apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-guest-book-prod
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prod
    name: in-cluster
  project: appbundle-production
  source:
    path: overlays/prod/guest-book
    repoURL: https://https://github.com/jdellostritto/k8s-ideal-goggles
    targetRevision: HEAD
    